# Generated by Django 5.0.6 on 2024-06-07 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('image', models.TimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_app.category')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.TextField()),
                ('answer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_accepted', models.BooleanField()),
                ('answer_to_compl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_app.complain')),
            ],
        ),
    ]
