# Generated by Django 5.0.6 on 2024-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_app', '0002_complain_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_adress',
            field=models.TextField(unique=True),
        ),
    ]
