# Generated by Django 5.0.6 on 2024-06-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_app', '0003_alter_user_home_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_adress',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
