# Generated by Django 5.0.6 on 2024-06-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_app', '0004_alter_user_home_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
